[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--fix", "--no-deps", "--allow-dirty"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.docs]
command = "cargo"
args = ["doc"]
