[workspace]
members = ["bin-packets", "jupiter-fsw", "ejector", "icarus", "ina260", "gs-cli", "common"]
exclude = ["gs-cli", "atmega"]
resolver = "3"

[profile.dev.package."atmega"]
opt-level = "s"

[profile.dev]
lto = true

[profile.release]
lto = true
