[toolchain]
channel = "nightly-2025-04-27"
targets = ["x86_64-unknown-linux-gnu","thumbv8m.main-none-eabihf", "aarch64-unknown-linux-gnu"]
components = ["rust-src", "rust-analyzer"]
profile = "default"