[env]
TARGET   = "avr-none"
CPU      = "atmega2560"
RUNNER   = "ravedude"
BUILDSTD = "core"
CARGO_TARGET_AVR_RUNNER = "${RUNNER}"
RUSTFLAGS = "-C target-cpu=${CPU} -C panic=abort"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.build]
command = "cargo"
args    = ["build",
           "--target", "${TARGET}",
           "-Z", "build-std=${BUILDSTD}"]   # nightly only

[tasks.build_release]
command = "cargo"
args    = ["build", "--release",
           "--target", "${TARGET}",
           "-Z", "build-std=${BUILDSTD}"]

[tasks.clippy]
extend  = "avr-env"
install_crate = "clippy"
command = "cargo"
args    = ["clippy", "--fix", "--allow-dirty",
           "--target", "${TARGET}"]

[tasks.test]
command = "echo"

[tasks.docs]
command = "cargo"
args = ["doc"]