[package]
name = "bin-packets"
version = "0.1.2"
edition = "2021"
publish = false

[dependencies]
bincode = { version = "*", features = ["derive"], default-features = false }
defmt = "*"
serde = { version = "*", features = ["derive"], default-features = false }

[features]
default = []
