[package]
name = "gs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.0"
serialport = "4.7.0"
bin-packets = {git = "https://github.com/Terminus-Suborbital-Research-Program/bin-packets.git"}
clap = { version = "4.5.31", features = ["derive"] }
