[package]
name = "gs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = {version = "2.0.0-rc.3", features = [
    "derive",
    "alloc",
]}
serialport = "4.7.0"
bin-packets = {path="../bin-packets"}
clap = { version = "4.5.31", features = ["derive"] }
