name: Rust build + Chores

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: davidB/rust-cargo-make@v1.12.1
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Install target
        run: rustup target add thumbv8m.main-none-eabihf
      - name: Test
        run: cargo make test --verbose

  clippy-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # only run on PRs
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      # checkout the PR branch with credentials so we can push back
      - name: Install deps
        run: sudo apt-get install -y libudev-dev pkg-config
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0           # fetch full history
          persist-credentials: true
      - uses: davidB/rust-cargo-make@v1.13.0
      - name: Install target
        run: rustup target add thumbv8m.main-none-eabihf
      - name: Run format
        run: cargo make format
      - name: Apply Clippy fixes
        run: cargo clippy --fix --allow-dirty
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply format + clippy fixes"